[versions]
spring-boot = "4.0.5"
hutool = "5.8.44"
mybatis-plus = "3.5.16"
mapstruct-plus = "1.5.0"
ip2region = "3.3.4"
redisson = "4.3.0"
redisson-cache = "4.3.0"
lock4j = "2.2.7"
guava = "33.5.0-jre"
commons-io = "2.21.0"
dynamic-datasource = "4.5.0"
p6spy = "3.9.1"
awssdk = "2.28.22"
fesod-sheet = "2.0.1-incubating"
bcprov-jdk15to18 = "1.80"

[libraries]
# BOM（约定插件中通过 platform() 引入，统一对齐版本）
spring-boot-bom = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "spring-boot" }
hutool-bom = { group = "cn.hutool", name = "hutool-bom", version.ref = "hutool" }
mybatis-plus-bom = { group = "com.baomidou", name = "mybatis-plus-bom", version.ref = "mybatis-plus" }
mapstruct-plus-bom = { group = "io.github.linpeilie", name = "mapstruct-plus-pom", version.ref = "mapstruct-plus" }
mapstruct-plus-processor = { group = "io.github.linpeilie", name = "mapstruct-plus-processor", version.ref = "mapstruct-plus" }

# Gradle 插件依赖（build-logic 自身使用）
spring-boot-gradle-plugin = { group = "org.springframework.boot", name = "spring-boot-gradle-plugin", version.ref = "spring-boot" }

ip2region = { group = "org.lionsoul", name = "ip2region", version.ref = "ip2region" }
redisson = { group = "org.redisson", name = "redisson-spring-boot-starter", version.ref = "redisson" }
redisson-cache = { group = "org.redisson", name = "redisson-spring-cache", version.ref = "redisson-cache" }
lock4j = { group = "com.baomidou", name = "lock4j-redisson-spring-boot-starter", version.ref = "lock4j" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commons-io" }
dynamic-datasource = { group = "com.baomidou", name = "dynamic-datasource-spring-boot4-starter", version.ref = "dynamic-datasource" }
p6spy = { group = "p6spy", name = "p6spy", version.ref = "p6spy" }
awssdk-s3 = { group = "software.amazon.awssdk", name = "s3", version.ref = "awssdk" }
awssdk-netty-nio-client = { group = "software.amazon.awssdk", name = "netty-nio-client", version.ref = "awssdk" }
awssdk-s3-transfer-manager = { group = "software.amazon.awssdk", name = "s3-transfer-manager", version.ref = "awssdk" }
fesod-sheet = { group = "org.apache.fesod", name = "fesod-sheet", version.ref = "fesod-sheet" }
bcprov-jdk15to18 = { group = "org.bouncycastle", name = "bcprov-jdk15to18", version.ref = "bcprov-jdk15to18" }

[plugins]
